# Generated by Django 3.1.7 on 2021-04-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('type', models.IntegerField()),
                ('point', models.IntegerField()),
                ('finishedCount', models.IntegerField()),
                ('haveTest', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
