# Generated by Django 3.1.7 on 2021-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210428_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignedTasks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
