# Generated by Django 3.1.7 on 2021-04-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.BigIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('taskCount', models.IntegerField()),
                ('finishedCount', models.IntegerField()),
                ('point', models.IntegerField()),
                ('gmtCreate', models.BigIntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('budget', models.IntegerField()),
                ('imgUrl', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('datasetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
                ('pictureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.picture')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.task')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'db_table': 'finished',
            },
        ),
    ]
