# Generated by Django 3.1.7 on 2021-04-29 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='gmtCreate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
