# Generated by Django 3.1.7 on 2021-04-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0003_auto_20210429_1542'),
        ('project', '0002_auto_20210429_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datasetId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset'),
        ),
    ]
