# Generated by Django 3.1.7 on 2021-04-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210429_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finishedCount',
            field=models.IntegerField(null=True),
        ),
    ]
