# Generated by Django 3.1.7 on 2021-05-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210429_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='answer',
            new_name='truth',
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.FloatField(null=True),
        ),
    ]
