# Generated by Django 3.1.7 on 2021-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210522_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
