# Generated by Django 3.1.7 on 2021-05-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hasFinished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='workerNum',
            field=models.IntegerField(default=0),
        ),
    ]
