# Generated by Django 3.1.7 on 2021-05-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_workers_qws'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batchNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='goldNum',
            field=models.IntegerField(default=0),
        ),
    ]
