# Generated by Django 3.1.7 on 2021-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210603_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='qws',
            new_name='acc',
        ),
        migrations.AddField(
            model_name='finished',
            name='isCurrent',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workers',
            name='acc_diff',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
