# Generated by Django 3.1.7 on 2021-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20210604_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished',
            name='isCurrent',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='acc',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='acc_diff',
        ),
        migrations.AddField(
            model_name='finished',
            name='batch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workers',
            name='batch',
            field=models.IntegerField(default=0),
        ),
    ]
