# Generated by Django 3.1.7 on 2021-06-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210605_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished',
            name='method',
            field=models.IntegerField(default=0),
        ),
    ]
